### ISSUE TITLE
DSA-Array-Python-Merge Intervals

### ISSUE THREAD

**Issue by jen-sjen** [das-jishu/python-stuff#1]
Hey there, I'm participating in #hactoberfest2k21, Please assign me the issue. Good day!
Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.
Example:
Input: intervals = [[1,3],[2,5]]
Output: [[1,5]]

**Comment by das-jishu** [comment]
Assigned. :)

**Comment by jen-sjen** [comment]
Thanks a lot!

**Comment by jen-sjen** [comment]
Hey, I have created a PR  :)
